name: Publish docker image
on:
  release:
    types:
      - published
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Getting version of project
        id: getting_project_version
        run: |
          echo "GUIABOLSO_CONNECTOR_VERSION=$(./gradlew version)" >> $GITHUB_ENV
          echo "DATADOG_VERSION=$(./gradlew properties --console=plain -q | grep "^datadog-version:" | awk '{print $2}')" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: checkout in release - ${{ github.event.release.tag_name }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Build and push release tag
        id: docker_build_tag
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            maiara/gt-actions:${{ github.event.release.tag_name }}
            maiara/gt-actions:latest
          build-args: |
            GUIABOLSO_CONNECTOR_VERSION=${{ env.GUIABOLSO_CONNECTOR_VERSION }}
            DATADOG_VERSION=${{ env.DATADOG_VERSION }}